<?xml version="1.0" encoding="utf-8"?>
<!--文本定义-->
<!DOCTYPE beans[
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref IDREF #IMPLIED>
]>
<beans>
        <bean id="userbasicdao" class="com.qqzone.dao.impl.userbasicdaoimpl"/>
        <bean id="topicdao" class="com.qqzone.dao.impl.topicdaoimpl"/>
        <bean id="replydao" class="com.qqzone.dao.impl.replydaoimpl"/>
        <bean id="hostreplydao" class="com.qqzone.dao.impl.hostreplydaoimpl"/>
        <bean id="userbasicservice" class="com.qqzone.service.impl.userbasicserviceImpl">
                <property name="userbasicdao" ref="userbasicdao"/>
        </bean>
        <bean id="hostreplyservice" class="com.qqzone.service.impl.hostreplyserviceimpl">
                <property name="hostreplydao" ref="hostreplydao"/>
        </bean>
        <bean id="replyservice" class="com.qqzone.service.impl.replyserviceimpl">
                <property name="replydao" ref="replydao"/>
                <property name="hostreplyservice" ref="hostreplyservice"/>
                <property name="userbasicservice" ref="userbasicservice"/>
        </bean>
        <bean id="topicservice" class="com.qqzone.service.impl.topicserviceimpl">
                <property name="topicdao" ref="topicdao"/>
                <property name="replyservice" ref="replyservice"/>
                <property name="userbasicservice" ref="userbasicservice"/>
        </bean>
        <bean id="reply" class="com.qqzone.controller.replycontroller">
                <property name="replyservice" ref="replyservice"/>
        </bean>
        <bean id="user" class="com.qqzone.controller.usercontroller">
                <property name="userbasicservice" ref="userbasicservice"/>
                <property name="topicservice" ref="topicservice"/>
        </bean>
        <bean id="page" class="com.qqzone.controller.pagecontroller"/>
        <bean id="topic" class="com.qqzone.controller.topiccontroller">
                <property name="topicservice" ref="topicservice"/>
        </bean>
</beans>





        <!--
        1.概念
        HTML : 超文本标记语言
        XML : 可扩展的标记语言
        HTML是XML的一个子集

        2.XML包含三个部分：
        1) XML声明 ， 而且声明这一行代码必须在XML文件的第一行
        2) DTD 文档类型定义
        3) XML正文
         -->